version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_petshop
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petshop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - petshop-net

volumes:
  mysql_data:

networks:
  petshop-net:
